### ISSUE TITLE
Scaling name correction

### ISSUE THREAD

**Issue by dschultzca** [pazi88/Siemens_ms45_RR-definitions#5]
In RomRaider ECU definitions the **<scaling name** attribute should be corrected to **<scaling category**    
The name attribute conflicts when inheriting from scalingbase elements.
https://www.romraider.com/index.php/RomRaider/EditorXMLReferenceGuide

In MS45 ECU Definitions v0.2.TJW.xml lines 271 & 279 need to be corrected.

**Comment by pazi88** [comment]
Fixed
